# Site Info
title: ConyCony's Blog
tagline: ConyCony's Blog
description: ''
logo: 
baseurl: ""
url: "http://conycony.github.io"
#url: "127.0.0.1:4000"

# Site configurations
plugins:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/categories/ALL/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: ConyCony
  description: 
  gravatar: 
  contact:
    github:    https://github.com/conyconydev
    # linkedin:  <hide>
    # facebook:  <hide>
    # twitter:   <hide>
    # weibo:     <hide>
    # email:     <hide>

future: true    
    
nav:
  Home:           
    - '/'
  Categories:
    - '/categories/CategoryList'
    - { All: '/categories/' }
    - { TIL: '/categories/TIL/' }
    - { Swift & Ios: '/categories/SwiftIos/' }
    - { Study: '/categories/Study/' }
    - { Project: '/categories/Project/' }
    - { Tags: '/categories/Tags/' }
  Github Project: 
    - 'https://github.com/conyconydev'


# Puglins
mathjax: false
google_analytics_token: 
disqus_short_name: "conyconydev-github-io"

theme: jekyll-theme-leap-day
