
name: ConyCony
description: Developer
avatar: https://avatars1.githubusercontent.com/u/43205384?s=460&v=4

footer-links:
  dribbble:
  email: conyconydev@gmail.com
  facebook:
  flickr:
  github: conyconydev
  instagram:
  linkedin:
  pinterest:
  rss: 
  twitter:
  stackoverflow: 
  youtube: 
  googleplus: 

google_analytics:
version: v1.2.0
  
permalink: pretty

navigation:
  - name: Archive
    url: /archive
  - name: Project
    url: /category/project
  - name: Daily
    url: /category/daily
  - name: Post
    url: /category/post
  - name: Education
    url: /category/education
  - name: Project_Tag
    url: /tags/project_tag
  - name: Daily_Tag
    url: /tags/daily_tag
  - name: Post_Tag
    url: /tags/post_tag
  - name: Education_Tag
    url: /tags/education_tag

disqus:
url:
baseurl:

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded 

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
